# Generated by Django 3.2.9 on 2025-02-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_auto_20190105_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='image',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
