# Generated by Django 3.2.9 on 2025-03-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210321_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
