# Generated by Django 3.2.9 on 2025-02-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_auto_20181229_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
